### PR TITLE
Add histogram equalization

### PR DESCRIPTION
**Pull request by Hsankesara**
@khilanravani  please check [gray scale image]( img/op4.jpg) and [image after histo filter](img/histo3.jpg).

### CODE REVIEW

**Comment by Hsankesara** [comment]
I believe Histogram equalization increase contrast way more than expected , What you think?

**Comment by khilanravani** [comment]
Yup. Agreed

**Comment by khilanravani** [comment]
We need to modify the filter so that the effects become milder than they are at present.

**Comment by Hsankesara** [comment]
@khilanravani you can see ```img_test'NUMBER'.jpeg``` as test images whose gray conversion stored as ```gray'NUMBER'.jpeg``` and histogram equalization conversions as ```histo'NUMBER'.jpeg```,
if you don't understand this please see the images added you'll get it.

**Review by khilanravani — COMMENTED** [review]
Yup. Getting what u are saying. I think that histogram equalization works better and results in a better raw output.

**Review by khilanravani — COMMENTED** [review]
Histo equalization is better I think coz at least the no. plate is clearly distinguished and readable. The contrast can be controlled I suppose. Not very sure.

**Comment by Hsankesara** [comment]
yep contrast can be controlled but it is in the best state as per my knowledge. can I merge this?

**Pull request merged**
